### ISSUE TITLE
Valid SDL seems to break tool.

### ISSUE THREAD

**Issue by hydrogen18** [Akashlytics/akashlytics-deploy#28]
Hello,

We were using your tool to demo our product (thanks!) and found we have a seemingly valid SDL that won't deploy via it.

This works from the command line tool

```
---
version: "2.0"

services:
  goosebin:
    image: ghcr.io/ovrclk/goosebin:20210902b
    expose:
      - port: 8000
        as: 80
        to:
          - global: true
  redis:
    image: redis:6.2.5
    expose:
      - port: 6379
    

profiles:
  compute:
    web:
      resources:
        cpu:
          units: 0.1
        memory:
          size: 128Mi
        storage:
          size: 128Mi
    storage:
      resources:
        cpu:
          units: 0.1
        memory:
          size: 512Mi
        storage:
          size: 128Mi
  placement:
    akash-verified:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
      pricing:
        web: 
          denom: uakt
          amount: 3000
        storage:
          denom: uakt
          amount: 3000

deployment:
  goosebin:
    akash-verified:
      profile: web
      count: 1
  redis:
    akash-verified:
      profile: storage
      count: 1
```

In the webapp it hits this message:

https://github.com/Akashlytics/akashlytics-deploy/blob/master/src/routes/CreateDeploymentWizard/ManifestEdit.js#L61

So we opened the dev tools & found this

```
2.c4a907ec.chunk.js:2 TypeError: Cannot read property 'forEach' of undefined
    at main.cec9c3a4.chunk.js:1
    at Array.forEach (<anonymous>)
    at main.cec9c3a4.chunk.js:1
    at Array.forEach (<anonymous>)
    at main.cec9c3a4.chunk.js:1
    at Array.forEach (<anonymous>)
    at pn (main.cec9c3a4.chunk.js:1)
    at main.cec9c3a4.chunk.js:1
    at c (2.c4a907ec.chunk.js:2)
    at Generator._invoke (2.c4a907ec.chunk.js:2)
    at Generator.next (2.c4a907ec.chunk.js:2)
    at r (2.c4a907ec.chunk.js:2)
    at s (2.c4a907ec.chunk.js:2)
    at 2.c4a907ec.chunk.js:2
    at new Promise (<anonymous>)
    at 2.c4a907ec.chunk.js:2
    at hn (main.cec9c3a4.chunk.js:1)
    at main.cec9c3a4.chunk.js:1
    at c (2.c4a907ec.chunk.js:2)
    at Generator._invoke (2.c4a907ec.chunk.js:2)
    at Generator.next (2.c4a907ec.chunk.js:2)
    at r (2.c4a907ec.chunk.js:2)
    at s (2.c4a907ec.chunk.js:2)
    at 2.c4a907ec.chunk.js:2
    at new Promise (<anonymous>)
    at 2.c4a907ec.chunk.js:2
    at I (main.cec9c3a4.chunk.js:1)
    at M (main.cec9c3a4.chunk.js:1)
    at main.cec9c3a4.chunk.js:1
    at c (2.c4a907ec.chunk.js:2)
    at Generator._invoke (2.c4a907ec.chunk.js:2)
    at Generator.next (2.c4a907ec.chunk.js:2)
    at r (2.c4a907ec.chunk.js:2)
    at s (2.c4a907ec.chunk.js:2)
    at 2.c4a907ec.chunk.js:2
    at new Promise (<anonymous>)
    at 2.c4a907ec.chunk.js:2
    at r (2.c4a907ec.chunk.js:2)
```

Seems to blow up on array iteration. Is three a way to run this so the filenames aren't obfuscated. I'm familiar with JS, but not with electron.
